// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.20.1
// source: remote_pubsub_messages.proto

package messages

import (
	actor "github.com/asynkron/protoactor-go/actor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemotePubSubMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      uint64     `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Topic   string     `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Message *anypb.Any `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *RemotePubSubMessage) Reset() {
	*x = RemotePubSubMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_pubsub_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemotePubSubMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemotePubSubMessage) ProtoMessage() {}

func (x *RemotePubSubMessage) ProtoReflect() protoreflect.Message {
	mi := &file_remote_pubsub_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemotePubSubMessage.ProtoReflect.Descriptor instead.
func (*RemotePubSubMessage) Descriptor() ([]byte, []int) {
	return file_remote_pubsub_messages_proto_rawDescGZIP(), []int{0}
}

func (x *RemotePubSubMessage) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *RemotePubSubMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *RemotePubSubMessage) GetMessage() *anypb.Any {
	if x != nil {
		return x.Message
	}
	return nil
}

type PubSubSubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestID  int64      `protobuf:"varint,1,opt,name=requestID,proto3" json:"requestID,omitempty"`
	Pattern    string     `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Subscriber *actor.PID `protobuf:"bytes,3,opt,name=subscriber,proto3" json:"subscriber,omitempty"`
}

func (x *PubSubSubscribeRequest) Reset() {
	*x = PubSubSubscribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_pubsub_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubSubSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubSubSubscribeRequest) ProtoMessage() {}

func (x *PubSubSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_pubsub_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubSubSubscribeRequest.ProtoReflect.Descriptor instead.
func (*PubSubSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_remote_pubsub_messages_proto_rawDescGZIP(), []int{1}
}

func (x *PubSubSubscribeRequest) GetRequestID() int64 {
	if x != nil {
		return x.RequestID
	}
	return 0
}

func (x *PubSubSubscribeRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *PubSubSubscribeRequest) GetSubscriber() *actor.PID {
	if x != nil {
		return x.Subscriber
	}
	return nil
}

type PubSubSubscribeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestID int64  `protobuf:"varint,1,opt,name=requestID,proto3" json:"requestID,omitempty"`
	Error     string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *PubSubSubscribeResponse) Reset() {
	*x = PubSubSubscribeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_pubsub_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubSubSubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubSubSubscribeResponse) ProtoMessage() {}

func (x *PubSubSubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_pubsub_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubSubSubscribeResponse.ProtoReflect.Descriptor instead.
func (*PubSubSubscribeResponse) Descriptor() ([]byte, []int) {
	return file_remote_pubsub_messages_proto_rawDescGZIP(), []int{2}
}

func (x *PubSubSubscribeResponse) GetRequestID() int64 {
	if x != nil {
		return x.RequestID
	}
	return 0
}

func (x *PubSubSubscribeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PubSubUnsubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestID  int64      `protobuf:"varint,1,opt,name=requestID,proto3" json:"requestID,omitempty"`
	Pattern    string     `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Subscriber *actor.PID `protobuf:"bytes,3,opt,name=subscriber,proto3" json:"subscriber,omitempty"`
}

func (x *PubSubUnsubscribeRequest) Reset() {
	*x = PubSubUnsubscribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_pubsub_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubSubUnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubSubUnsubscribeRequest) ProtoMessage() {}

func (x *PubSubUnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_pubsub_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubSubUnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*PubSubUnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_remote_pubsub_messages_proto_rawDescGZIP(), []int{3}
}

func (x *PubSubUnsubscribeRequest) GetRequestID() int64 {
	if x != nil {
		return x.RequestID
	}
	return 0
}

func (x *PubSubUnsubscribeRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *PubSubUnsubscribeRequest) GetSubscriber() *actor.PID {
	if x != nil {
		return x.Subscriber
	}
	return nil
}

type PubSubUnsubscribeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestID int64 `protobuf:"varint,1,opt,name=requestID,proto3" json:"requestID,omitempty"`
}

func (x *PubSubUnsubscribeResponse) Reset() {
	*x = PubSubUnsubscribeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_pubsub_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubSubUnsubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubSubUnsubscribeResponse) ProtoMessage() {}

func (x *PubSubUnsubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_pubsub_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubSubUnsubscribeResponse.ProtoReflect.Descriptor instead.
func (*PubSubUnsubscribeResponse) Descriptor() ([]byte, []int) {
	return file_remote_pubsub_messages_proto_rawDescGZIP(), []int{4}
}

func (x *PubSubUnsubscribeResponse) GetRequestID() int64 {
	if x != nil {
		return x.RequestID
	}
	return 0
}

type PubSubUnsubscribeAll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subscriber *actor.PID `protobuf:"bytes,4,opt,name=subscriber,proto3" json:"subscriber,omitempty"`
}

func (x *PubSubUnsubscribeAll) Reset() {
	*x = PubSubUnsubscribeAll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_pubsub_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubSubUnsubscribeAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubSubUnsubscribeAll) ProtoMessage() {}

func (x *PubSubUnsubscribeAll) ProtoReflect() protoreflect.Message {
	mi := &file_remote_pubsub_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubSubUnsubscribeAll.ProtoReflect.Descriptor instead.
func (*PubSubUnsubscribeAll) Descriptor() ([]byte, []int) {
	return file_remote_pubsub_messages_proto_rawDescGZIP(), []int{5}
}

func (x *PubSubUnsubscribeAll) GetSubscriber() *actor.PID {
	if x != nil {
		return x.Subscriber
	}
	return nil
}

var File_remote_pubsub_messages_proto protoreflect.FileDescriptor

var file_remote_pubsub_messages_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x70, 0x75, 0x62, 0x73, 0x75, 0x62, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x73, 0x79, 0x6e, 0x6b, 0x72, 0x6f, 0x6e, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2d, 0x67, 0x6f, 0x2f, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x2f, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61,
	0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6b, 0x0a, 0x13, 0x52, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x50, 0x75, 0x62, 0x53, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x2e, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x7c, 0x0a, 0x16, 0x50, 0x75, 0x62, 0x53, 0x75, 0x62, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x12, 0x2a, 0x0a, 0x0a, 0x73, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x63,
	0x74, 0x6f, 0x72, 0x2e, 0x50, 0x49, 0x44, 0x52, 0x0a, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x72, 0x22, 0x4d, 0x0a, 0x17, 0x50, 0x75, 0x62, 0x53, 0x75, 0x62, 0x53, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0x7e, 0x0a, 0x18, 0x50, 0x75, 0x62, 0x53, 0x75, 0x62, 0x55, 0x6e, 0x73, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70,
	0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x12, 0x2a, 0x0a, 0x0a, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x2e, 0x50, 0x49, 0x44, 0x52, 0x0a, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x72, 0x22, 0x39, 0x0a, 0x19, 0x50, 0x75, 0x62, 0x53, 0x75, 0x62, 0x55, 0x6e, 0x73, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x22, 0x42, 0x0a,
	0x14, 0x50, 0x75, 0x62, 0x53, 0x75, 0x62, 0x55, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x41, 0x6c, 0x6c, 0x12, 0x2a, 0x0a, 0x0a, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x2e, 0x50, 0x49, 0x44, 0x52, 0x0a, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x72, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x74, 0x69, 0x63, 0x6b, 0x73, 0x2f, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x2d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_remote_pubsub_messages_proto_rawDescOnce sync.Once
	file_remote_pubsub_messages_proto_rawDescData = file_remote_pubsub_messages_proto_rawDesc
)

func file_remote_pubsub_messages_proto_rawDescGZIP() []byte {
	file_remote_pubsub_messages_proto_rawDescOnce.Do(func() {
		file_remote_pubsub_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_remote_pubsub_messages_proto_rawDescData)
	})
	return file_remote_pubsub_messages_proto_rawDescData
}

var file_remote_pubsub_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_remote_pubsub_messages_proto_goTypes = []interface{}{
	(*RemotePubSubMessage)(nil),       // 0: messages.RemotePubSubMessage
	(*PubSubSubscribeRequest)(nil),    // 1: messages.PubSubSubscribeRequest
	(*PubSubSubscribeResponse)(nil),   // 2: messages.PubSubSubscribeResponse
	(*PubSubUnsubscribeRequest)(nil),  // 3: messages.PubSubUnsubscribeRequest
	(*PubSubUnsubscribeResponse)(nil), // 4: messages.PubSubUnsubscribeResponse
	(*PubSubUnsubscribeAll)(nil),      // 5: messages.PubSubUnsubscribeAll
	(*anypb.Any)(nil),                 // 6: google.protobuf.Any
	(*actor.PID)(nil),                 // 7: actor.PID
}
var file_remote_pubsub_messages_proto_depIdxs = []int32{
	6, // 0: messages.RemotePubSubMessage.message:type_name -> google.protobuf.Any
	7, // 1: messages.PubSubSubscribeRequest.subscriber:type_name -> actor.PID
	7, // 2: messages.PubSubUnsubscribeRequest.subscriber:type_name -> actor.PID
	7, // 3: messages.PubSubUnsubscribeAll.subscriber:type_name -> actor.PID
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_remote_pubsub_messages_proto_init() }
func file_remote_pubsub_messages_proto_init() {
	if File_remote_pubsub_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_remote_pubsub_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemotePubSubMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_pubsub_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubSubSubscribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_pubsub_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubSubSubscribeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_pubsub_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubSubUnsubscribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_pubsub_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubSubUnsubscribeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_pubsub_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubSubUnsubscribeAll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_remote_pubsub_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_remote_pubsub_messages_proto_goTypes,
		DependencyIndexes: file_remote_pubsub_messages_proto_depIdxs,
		MessageInfos:      file_remote_pubsub_messages_proto_msgTypes,
	}.Build()
	File_remote_pubsub_messages_proto = out.File
	file_remote_pubsub_messages_proto_rawDesc = nil
	file_remote_pubsub_messages_proto_goTypes = nil
	file_remote_pubsub_messages_proto_depIdxs = nil
}
